//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ploteus.TR.Client.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ploteus.TR.Client.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;tns:LearningOpportunities 
        ///	Incremental=&quot;false&quot; 
        ///	Key=&quot;to be provided by Intrasoft&quot; 
        ///	XsdType=&quot;Learning Opportunity&quot; XsdVersion=&quot;0.5.10&quot; 
        ///	xmlns:tns=&quot;http://ec.europa.eu/LearningOpportunities/v0_5_10&quot; 
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///	xsi:schemaLocation=&quot;http://ec.europa.eu/LearningOpportunities/v0_5_10 learningOpportunities_v0.5.10.xsd &quot;&gt;
        ///	&lt;tns:LearningOpportunity&gt;
        ///		&lt;tns:LearningOpportunityId&gt;LearningOpportunityId1&lt;/tns:LearningOppor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lo_full_sample {
            get {
                return ResourceManager.GetString("lo_full_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;tns:Qualifications xmlns:tns=&quot;http://ec.europa.eu/Qualifications/v0_7_10&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; DatasourceComment=&quot;This is the datasource comment&quot; Incremental=&quot;true&quot; Key=&quot;to be provided by Intrasoft&quot; XsdType=&quot;Qualification&quot; XsdVersion=&quot;0.7.10&quot; xsi:schemaLocation=&quot;http://ec.europa.eu/Qualifications/v0_7_10 qualifications_v0.7.10.xsd &quot;&gt;
        ///  &lt;tns:Qualification&gt;
        ///    &lt;tns:QualificationId&gt;QualificationId2&lt;/tns:QualificationId&gt;
        ///    &lt;tns:Title&gt;Ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string qual_full_sample_xml {
            get {
                return ResourceManager.GetString("qual_full_sample_xml", resourceCulture);
            }
        }
    }
}
